<?php

use Drupal\Core\Breadcrumb\Breadcrumb;
use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Cache\CacheableMetadata;
use Drupal\urct\ReferralUrlHandler;
use Drupal\urct\UrctPathBasedBreadcrumbBuilder;

/**
 * Implements hook_system_breadcrumb_alter().
 */
function urct_system_breadcrumb_alter(Breadcrumb &$breadcrumb, RouteMatchInterface $route_match, array $context) {

  $request_context = \Drupal::service('router.request_context');
  if ( !($context['builder'] instanceof UrctPathBasedBreadcrumbBuilder) && \Drupal::currentUser()->isAnonymous() && $referral_item = ReferralUrlHandler::getReferralFromPath($request_context->getPathInfo())) {
    $links = $breadcrumb->getLinks();

    $count_current_path = count(explode('/', $request_context->getPathInfo()));
    $count_normal_path = count(explode('/', $referral_item->normal_path));

    array_splice($links, count($link - ($count_current_path - $count_normal_path)));

    // Links cannot be removed from an existing breadcrumb object. Create a new
    // object but carry over the cacheable metadata.
    $cacheability = CacheableMetadata::createFromObject($breadcrumb);
    $breadcrumb = new Breadcrumb();
    $breadcrumb->setLinks($links);
    $breadcrumb->addCacheableDependency($cacheability);
  }
}