# Schema for the configuration files of the urct module.

urct.settings:
  type: config_object
  label: 'User Referral Settings'
  mapping:
    fallback_type:
      type: string
      label: 'Fallback user selection'
